version: '3.8'

services:
  aggregator:
    build:
      context: .             # Set the context to the root level
      dockerfile: aggregator/Dockerfile  # Specify the Dockerfile path
    ports:
      - "8005:8005"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
